Fix CMake package config file
google/or-tools pull request #3068
Opened 2022-01-11 21:51 UTC by gmgunter

There are currently a few issues with how the COIN-OR dependencies are resolved when using `find_package(ortools CONFIG)` to add or-tools to an external CMake project.

* With CMake >=3.9.6, we try to find the Clp and Cbc packages using the CONFIG mode of `find_package`. This always fails since neither [coin-or/Clp](https://github.com/coin-or/Clp) nor [coin-or/Cbc](https://github.com/coin-or/Cbc) provides a CMake config file.

* If we address the above issue by instead using the MODULE mode of `find_package`, then we need to add `FindCbc.cmake` and `FindCpl.cmake` scripts to the CMAKE_MODULE_PATH in order to teach CMake how to find these dependencies. I propose that or-tools should install these scripts alongside its config file so that they're available to external CMake projects.

* Finally, the `FindCbc.cmake` script included with or-tools defines the variable `CBC_FOUND` when it's successful, rather than `Cbc_FOUND` as expected ([CMake variables are case-sensitive](https://stackoverflow.com/a/35034125)). The `FindCpl.cmake` script has a similar issue. As a result, even when the above two points are addressed, `find_package(ortools CONFIG)` will still fail because CMake erroneously thinks that these two dependencies weren't succesfully found.

This PR attempts to address the above issues with the following changes:

* The CMake config file is modified to allow searching for Cbc and Cpl using the MODULE mode of `find_package`.

* `FindCbc.cmake` and `FindCpl.cmake` are installed with the CMake package config files and are added to the CMAKE_MODULE_PATH if `USE_COINOR` was truthy.

* The `FindCbc.cmake` and `FindCpl.cmake` files are modified to change the case of the variables they export.

2022-01-11 23:17 UTC, Mizux commented
1) I've fork coin-or few years ago to add CMake support, they never want to integrate it...

2022-01-12 00:45 UTC, gmgunter commented
>I've forked coin-or repos (Cbc, Clp, Cgl, Osi, CoinUtils) few years ago to add CMake support, they never want to integrate it...

That's too bad. The most elegant solution would definitely be for these upstream packages to add CMake support.

>Need a job to test the CMake based build of or-tools against coin-or installed system-wide

This would be really nice. I installed or-tools via the [conda-forge package](https://anaconda.org/conda-forge/ortools-cpp), which builds with [`BUILD_DEPS=OFF`](https://github.com/conda-forge/or-tools-feedstock/blob/c331915da5c25ecabb4d73633d503f7427c5cf1e/recipe/build-cpp.sh#L7).

2022-01-12 09:58 UTC, Mizux requested changes

2022-01-12 09:58 UTC, Mizux commented on cmake/cpp.cmake
> +install(
can you guard it with a `if(USE_COINOR)`, i.e. if the coin-or support is disable there is no interest to install module

2022-01-12 23:17 UTC, Mizux approved these changes

2022-01-14 07:38 UTC, merged

2022-01-19 13:00 UTC, Mizux commented
FYI I'll need to change the module CMake since:
1. It does not support super build i.e. if Cbc target already present the module should be a noop
2. It does not support cbc_config.cmake file (like we have when building cbc or using vcpkg) so first module should try a to perform a find_package( CONFIG) then if found -> nothing to do, otherwise try to locate it using the pkg plugin...

On my way to fix it, if you have some regression in your worflow, please let me know...

2022-01-19 18:42 UTC, gmgunter commented
Sounds good :ok_hand:

2023-02-02 21:56 UTC, Neumann-A commented
@Mizux I'll probably be the one to rip out all the `CMakeLists.txt` vcpkg vendors. Including any exported targets which have been added and are currently in disagreement with the maintainer guidelines of vcpkg. Either you get upstream to accept your CMake versions or pkg-config will be the preferred way to consume coin-or libraries.

2023-02-03 08:09 UTC, Mizux commented
@Neumann-A
1. Do you have a link to this maintainer guidelines assertion ?
2. Does pkg-config build will work on Windows and nicely integrate with vcpkg ?
3. How to deal (nicely) with a CMake toolchain file if using pkg-config/autotools based build ?
4. How about having a Community supported CMake fork ?

note: here pkg-config/autotools based build means what coin-or provide if I understand correctly your point
note2: IIRC it was a user of openframework who provide a first ugly CMakeLists.txt patch on vcpkg

2023-02-03 08:20 UTC, Neumann-A commented
> Do you have a link to this maintainer guidelines assertion ?

a) The current name of most coin-or ports in vcpkg is wrong according to https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#check-names-against-other-repositories (basically the ports need a prefix `coin-or-*`

b) `unofficial::` namespace: https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md#add-cmake-exports-in-an-unofficial--namespace

> Does pkg-config build will work on Windows and nicely integrate with vcpkg ?
> How to deal (nicely) with a CMake toolchain file if using pkg-config/autotools based build ?

vcpkg has a port for pkgconf. If it is installed CMake's`FindPkgConfig` will automatically start working. be aware that it breaks multi-config usage (e.g. no interactive switching of the build type, as long as you stay with one build type you are fine). For ports internal to vcpkg it will start to automatically work due to how the `vcpkg_` function are setup and if additional downstream usage agrees with upstream provided usage. 

> How about having a Community supported CMake fork ?

No. Upstream it or leave it. Source packages have to come from the authoritative source. 

So I already started ripping it out: https://github.com/microsoft/vcpkg/pull/29398. basically the only thing left to do is fixing openmvg and getting the linux VM to have autoconf 2.71